---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-api
  namespace: default
  labels:
    app: test-api
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: test-api
  template:
    metadata:
      labels:
        app: test-api
    spec:
      initContainers:
        - image: k8s.gcr.io/git-sync:v3.1.5
          name: init-sync
          volumeMounts:
            - name: app-dir
              mountPath: /tmp/git
          env:
            - name: GIT_SYNC_REPO
              value: https://github.com/jonje/spring-boot-kube-deployment.git
            - name: GIT_SYNC_BRANCH
              value: main
            - name: GIT_SYNC_DEPTH
              value: "1"
            - name: GIT_SYNC_DEST
              value: "code"
            - name: GIT_SYNC_ONE_TIME
              value: "true"
        - image: maven:3.8-amazoncorretto-11
          name: init-mvn-build
          volumeMounts:
            - name: app-dir
              mountPath: /usr/src/myapp
          env:
          workingDir: /usr/src/myapp/code
          command:
            - "mvn"
            - "clean"
            - "package"
            - "-DskipTests"
#          command: [ "/bin/bash" ]
#          args: [ "-c", "ls" ]
      containers:
        - name: test-api
          image: eclipse-temurin:11-jre-alpine
          workingDir: /usr/src/myapp/code/target
          command:
            - "java"
            - "-jar"
            - "app.jar"
#          command: ["/bin/sh"]
#          args: ["-c", "ls"]
          volumeMounts:
            - name: app-dir
              mountPath: /usr/src/myapp
      volumes:
        - name: app-dir
          emptyDir: {}